# Parameters for adaptive_grasping package
# Remember that there can be other important constants that can only be changed
# from the src code.

adaptive_grasping:
  # The topic where the finger touches data is published
  touch_topic_name: "/touching_finger_topic"
  # The following map contains the correspondance between ids and link names
  link_names_map:
    "1" : "right_hand_thumb_distal_link"
    "2" : "right_hand_index_distal_link"
    "3" : "right_hand_middle_distal_link"
    "4" : "right_hand_ring_distal_link"
    "5" : "right_hand_little_distal_link"
  # The following map contains other necessary params for adaptive_grasping
  params_map:
    world_name: "world"
    palm_name: "right_arm_7_link"
    ee_name: "right_hand_ee_link"
  # The array containing the number of links of each finger
  joints_num: [5, 7, 7, 7, 7]
  # The following list of arrays is the contact selection matrix H
  h_matrix:
    - [1, 0, 0, 0, 0, 0]
    - [0, 1, 0, 0, 0, 0]
    - [0, 0, 1, 0, 0, 0]
    - [0, 0, 0, 1, 0, 0]
    - [0, 0, 0, 0, 1, 0]
    - [0, 0, 0, 0, 0, 1]
  # The following list of arrays is the minimization weight matrix A tilde
  a_tilde_matrix:
    - [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 10000, 0, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0, 10000, 0, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0, 0, 10000, 0, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10000, 0, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10000, 0]
    - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10000]
  # The following array is the desired x motion
  x_d:
    # - [0.1, 0, 0, -0.01, 0, -0.05, 0, 0, 0, 0, 0, 0, 0]     # for other fingers mainly?
    - [0.1, 0, 0, -0.01, 0.05, 0, 0, 0, 0, 0, 0, 0, 0]    # for thumb mainly?
  # The rate of the adaptive loop
  spin_rate: 1000.0
  # The topic where the object pose is published
  object_topic_name: "/object_pose_topic"
  # The scaling factor for the reference motion
  scaling: 1.0
  # The permutation vector for relaxed minimization (the elements of the vector stand for the reordering of the rows of Q)
  p_vector:
    - [1, 2, 4, 5, 6, 3]    # for relaxing only the velocity along local z


